# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# A deliberately messy table: missing values, blank strings, invalid numbers,
# invalid dates, and one extra column with bad email values.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', None, '???'],
    'Age': ['25', 'thirty', 35, np.nan, '40', 'old'],
    'Signup Date': ['2022-01-01', 'not a date', '2022/03/01', None, 'April 5, 2022', 'not sure'],
    'Score': [95.5, None, 88.0, 92.5, '', 'A+'],
    'Email': ['alice@example.com', None, '', 'david@example.com', 'missing@example.com', 'bad-email'],
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score                Email
0    Alice      25     2022-01-01  95.5    alice@example.com
1      Bob  thirty     not a date  None                  NaN
2  Charlie      35     2022/03/01  88.0
3    David     NaN            NaN  92.5    david@example.com
4      NaN      40  April 5, 2022        missing@example.com
5      ???     old       not sure    A+            bad-email

### 🧯 2. Detecting Missing or Broken Values

In [2]:
df.isnull()

    Name    Age  Signup Date  Score  Email
0  False  False        False  False  False
1  False  False        False   True   True
2  False  False        False  False  False
3  False   True         True  False  False
4   True  False        False  False  False
5  False  False        False  False  False

In [3]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
Email          1
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score                Email
1    Bob  thirty     not a date  None                  NaN
3  David     NaN            NaN  92.5    david@example.com
4    NaN      40  April 5, 2022        missing@example.com

### 🧹 3. Cleaning Strategy Options

In [5]:
df.fillna({
    'Name': 'Unknown',
    'Age': -1,
    'Signup Date': '1970-01-01',
    'Score': 0.0,
    'Email': 'unknown@example.com',
})

      Name     Age    Signup Date Score                Email
0    Alice      25     2022-01-01  95.5    alice@example.com
1      Bob  thirty     not a date   0.0  unknown@example.com
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5    david@example.com
4  Unknown      40  April 5, 2022        missing@example.com
5      ???     old       not sure    A+            bad-email

In [6]:
df.dropna()

      Name  Age Signup Date Score              Email
0    Alice   25  2022-01-01  95.5  alice@example.com
2  Charlie   35  2022/03/01  88.0
5      ???  old    not sure    A+          bad-email

### 🧬 4. Data Type Fixes

In [7]:
df.dtypes

Name              str
Age            object
Signup Date       str
Score          object
Email             str
dtype: object

In [8]:
# Convert blank strings to NaN first, then coerce invalid numbers/dates to NaN.
df = df.replace('', np.nan)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Score'] = pd.to_numeric(df['Score'], errors='coerce')
df['Signup Date'] = pd.to_datetime(df['Signup Date'], errors='coerce')
df.dtypes

Name                      str
Age                   float64
Signup Date    datetime64[us]
Score                 float64
Email                     str
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Score'] = df['Score'].fillna(df['Score'].mean())

In [10]:
df['Signup Date'] = df['Signup Date'].fillna(df['Signup Date'].min())

In [11]:
df['Name'] = df['Name'].fillna('Unknown')
df['Email'] = df['Email'].fillna('unknown@example.com')
df

      Name   Age Signup Date  Score                Email
0    Alice  25.0  2022-01-01   95.5    alice@example.com
1      Bob  35.0  2022-01-01   92.0  unknown@example.com
2  Charlie  35.0  2022-01-01   88.0  unknown@example.com
3    David  35.0  2022-01-01   92.5    david@example.com
4  Unknown  40.0  2022-01-01   92.0  missing@example.com
5      ???  35.0  2022-01-01   92.0            bad-email

### 🤓 6. Cleaned Data Review

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         6 non-null      str
 1   Age          6 non-null      float64
 2   Signup Date  6 non-null      datetime64[us]
 3   Score        6 non-null      float64
 4   Email        6 non-null      str
dtypes: datetime64[us](1), float64(2), str(2)
memory usage: 372.0 bytes

In [13]:
df.describe(include="all")

         Name        Age          Signup Date      Score                Email
count       6   6.000000                    6   6.000000                    6
unique      6        NaN                  NaN        NaN                    5
top     Alice        NaN                  NaN        NaN  unknown@example.com
freq        1        NaN                  NaN        NaN                    2
mean      NaN  34.166667  2022-01-01 00:00:00  92.000000                  NaN
min       NaN  25.000000  2022-01-01 00:00:00  88.000000                  NaN
25%       NaN  35.000000  2022-01-01 00:00:00  92.000000                  NaN
50%       NaN  35.000000  2022-01-01 00:00:00  92.000000                  NaN
75%       NaN  35.000000  2022-01-01 00:00:00  92.375000                  NaN
max       NaN  40.000000  2022-01-01 00:00:00  95.500000                  NaN
std       NaN   4.915960                  NaN   2.387467                  NaN

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [14]:
# Mini-challenge: load and clean the messy survey data.
SURVEY_PATH = Path('Assignments/01-Python_Foundations/05-Working_with_Data_Adv/data/survey.csv')
if not SURVEY_PATH.exists():
    SURVEY_PATH = Path('../../data/survey.csv')

survey = pd.read_csv(SURVEY_PATH)
print('Original shape:', survey.shape)
print()
print('Missing values before cleaning:')
print(survey.isnull().sum().sort_values(ascending=False).head(10))

clean = survey.copy()

# Standardize obvious text categories.
clean['major'] = clean['major'].replace({'CompSci': 'Computer Science', 'CS': 'Computer Science'})
clean['gender'] = clean['gender'].fillna('Unknown').str.strip().str.title()
clean['dorm_resident'] = clean['dorm_resident'].fillna('Unknown').str.strip().str.title()
clean['favorite_language'] = clean['favorite_language'].fillna('Unknown').str.strip()
clean['comments'] = clean['comments'].fillna('No comment')

# Convert numeric-looking columns and mark impossible values as missing.
numeric_columns = ['age', 'gpa', 'study_hours_per_week', 'satisfaction_1_5', 'expected_grad_year', 'commute_minutes']
for column in numeric_columns:
    clean[column] = pd.to_numeric(clean[column], errors='coerce')

clean.loc[~clean['age'].between(16, 80), 'age'] = np.nan
clean.loc[~clean['gpa'].between(0, 4), 'gpa'] = np.nan
clean.loc[clean['study_hours_per_week'] < 0, 'study_hours_per_week'] = np.nan
clean.loc[~clean['satisfaction_1_5'].between(1, 5), 'satisfaction_1_5'] = np.nan
clean.loc[clean['commute_minutes'] < 0, 'commute_minutes'] = np.nan

# Attendance rate has percent strings like '105%'. Convert to a 0-100 numeric rate.
clean['attendance_rate'] = clean['attendance_rate'].astype(str).str.rstrip('%')
clean['attendance_rate'] = pd.to_numeric(clean['attendance_rate'], errors='coerce')
clean.loc[~clean['attendance_rate'].between(0, 100), 'attendance_rate'] = np.nan

# Convert dates. Invalid dates become NaT.
clean['survey_date'] = pd.to_datetime(clean['survey_date'], errors='coerce')

# Fill remaining values with simple course-appropriate defaults.
for column in ['age', 'gpa', 'study_hours_per_week', 'satisfaction_1_5', 'commute_minutes', 'attendance_rate']:
    clean[column] = clean[column].fillna(clean[column].median())

clean['expected_grad_year'] = clean['expected_grad_year'].fillna(clean['expected_grad_year'].mode()[0])
clean['income_range'] = clean['income_range'].fillna('Unknown')
clean['clubs_member'] = clean['clubs_member'].fillna('Unknown')
clean['survey_date'] = clean['survey_date'].fillna(clean['survey_date'].min())

print()
print('Missing values after cleaning:')
print(clean.isnull().sum().sort_values(ascending=False).head(10))
print()
print('Cleaned info:')
clean.info()

clean.describe(include='all')

Original shape: (120, 16)

Missing values before cleaning:
attendance_rate         79
commute_minutes         53
comments                52
satisfaction_1_5        46
gpa                     44
study_hours_per_week    42
age                     33
dorm_resident           33
expected_grad_year      33
survey_date             32
dtype: int64

Missing values after cleaning:
major                   10
student_id               0
age                      0
gender                   0
gpa                      0
study_hours_per_week     0
satisfaction_1_5         0
survey_date              0
dorm_resident            0
expected_grad_year       0
dtype: int64

Cleaned info:
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   120 non-null    float64
 2   gender                120 non-null    str
 3   major                 110 non-null    str
 4   gpa                   120 non-null    float64
 5   study_hours_per_week  120 non-null    float64
 6   satisfaction_1_5      120 non-null    float64
 7   survey_date           120 non-null    datetime64[us]
 8   dorm_resident         120 non-null    str
 9   expected_grad_year    120 non-null    float64
 10  income_range          120 non-null    str
 11  commute_minutes       120 non-null    float64
 12  clubs_member          120 non-null    str
 13  attendance_rate       120 non-null    float64
 14  favorite_language     120 non-null    str
 15  comments              120 non-null    str
dtypes: datetime64[us](1), float64(7), str(8)
memory usage: 15.1 KB

/var/folders/kp/2bl6xl8n4939qvvlvq_fc8500000gn/T/ipykernel_288/810388220.py:38: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean['survey_date'] = pd.to_datetime(clean['survey_date'], errors='coerce')

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
count,120,120.000000,120,110,120.000000,120.000000,120.000000,120,120,120.000000,120,120.000000,120,120.000000,120,120
unique,120,NaN,5,7,NaN,NaN,NaN,NaN,5,NaN,7,NaN,7,NaN,8,5
top,S10000,NaN,Male,Computer Science,NaN,NaN,NaN,NaN,Unknown,NaN,>$100k,NaN,1,NaN,Unknown,No comment
freq,1,NaN,28,37,NaN,NaN,NaN,NaN,33,NaN,22,NaN,25,NaN,19,52
mean,NaN,21.158333,NaN,NaN,3.706417,12.533333,2.941667,2025-09-26 20:24:00,NaN,2027.583333,NaN,15.858333,NaN,83.833333,NaN,NaN
min,NaN,18.000000,NaN,NaN,2.030000,0.000000,1.000000,2025-09-02 00:00:00,NaN,2026.000000,NaN,0.000000,NaN,62.000000,NaN,NaN
25%,NaN,20.000000,NaN,NaN,3.750000,12.500000,3.000000,2025-09-02 00:00:00,NaN,2027.000000,NaN,15.000000,NaN,84.000000,NaN,NaN
50%,NaN,21.000000,NaN,NaN,3.750000,12.500000,3.000000,2025-09-03 00:00:00,NaN,2027.000000,NaN,15.000000,NaN,84.000000,NaN,NaN
75%,NaN,22.000000,NaN,NaN,3.750000,12.500000,3.000000,2025-10-28 12:00:00,NaN,2028.000000,NaN,15.000000,NaN,84.000000,NaN,NaN
max,NaN,25.000000,NaN,NaN,3.920000,30.000000,5.000000,2025-11-30 00:00:00,NaN,2030.000000,NaN,75.000000,NaN,99.000000,NaN,NaN
std,NaN,1.887579,NaN,NaN,0.243551,5.623605,0.891565,NaN,NaN,1.170960,NaN,12.354223,NaN,4.536191,NaN,NaN

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |